apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
spec:
  selector:
    app: streamlit-ai-agent
  ports:
  - port: 80          # Service port exposed internally
    targetPort: 8501  # Container port inside the pod
    nodePort: 30008   # External port on the node
  type: NodePort

